# Generated by Django 3.2.4 on 2021-07-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_lite_app', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
