# Generated by Django 3.2.4 on 2021-07-28 09:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_lite_app', '0004_post_imagee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagee',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
